Repository GSG-G11/newsProject-TheTriples, pull requests merged in 2022-02, with the labels that each got.

#3 Add README.md Content
  README.md
Labels: Awaiting Review

#5 create folder structure
  Details/details.css
  Details/details.html
  images/banner.jpg
  index.html
  style.css
Labels: Awaiting Review

#12 Create Footer Section
  images/logo.svg
  index.html
  style.css
Labels: Awaiting Review

#15 create Navbar-mainnews
  images/68747470733a2f2f73766773686172652e636f6d2f692f64726b2e737667.svg
  index.html
  style.css
Labels: Done

#22 Styling header links and implement smooth scroll
  index.html
  style.css
Labels: Awaiting Review

#21 Create side bar
  images/pop1.jpg
  images/pop2.jpg
  images/pop3.jpg
  index.html
  style.css
Labels: Done

#26 Make main page responsive
  index.html
  style.css
Labels: Done

#23 adding header and footer
  Details/details.css
  Details/details.html
  style.css
Labels: Awaiting Review

#27 Edit some Styling
  style.css
Labels: Done

#32 Solved issues in main page
  index.html
  style.css
Labels: issues-solved
